name: Build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: Install Pico SDK and toolchain
      run: |
        git clone -b "1.5.1" --depth=1 https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init --depth=1
        cd ..
        sudo apt-get update
        sudo apt-get install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
    - name: Build binaries
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
      run: |
        cmake -B build
        make -C build
    - name: Save binary as release
      uses: "czietz/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest firmware"
        prerelease: false
        files: |
          build/debug.uf2

